apiVersion: v1
kind: Service
metadata:
  name: flask-calculator-service
  namespace: calc-app-ns
spec:
  selector:
    app: calc-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30100
  type: NodePort